{
 "title": "Car Parking System",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Vehicle Gates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Entry Vehicle Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "entrycarcount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exit Vehicle Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "exitcarcount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Parking Slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "SLOT 1 STATUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 1, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "STATUS",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "measurement": "availability",
     "query": "SELECT last(\"value\") FROM \"availability\" WHERE (\"slot\" = 'SLOT 1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "slot", "operator": "=", "value": "SLOT 1" },
      { "condition": "AND", "key": "value", "operator": "!=", "value": "IGNORED" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SLOT 2 STATUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "STATUS",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "measurement": "availability",
     "query": "SELECT last(\"value\")  FROM \"availability\"  WHERE (\"slot\" = 'SLOT 1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "slot", "operator": "=", "value": "SLOT 2" },
      { "condition": "AND", "key": "value", "operator": "!=", "value": "IGNORED" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SLOT 3 STATUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "STATUS",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "measurement": "availability",
     "query": "SELECT last(\"value\")  FROM \"availability\"  WHERE (\"slot\" = 'SLOT 1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "slot", "operator": "=", "value": "SLOT 3" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SLOT 4 STATUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "STATUS",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "measurement": "availability",
     "query": "SELECT last(\"value\")  FROM \"availability\"  WHERE (\"slot\" = 'SLOT 1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "slot", "operator": "=", "value": "SLOT 4" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SLOT 1 ACCURACY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 1, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "STATUS",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "measurement": "correctness",
     "query": "SELECT last(\"value\")  FROM \"availability\"  WHERE (\"slot\" = 'SLOT 1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "slot", "operator": "=", "value": "SLOT 1" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SLOT 2 ACCURACY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "STATUS",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "measurement": "correctness",
     "query": "SELECT last(\"value\")  FROM \"availability\"  WHERE (\"slot\" = 'SLOT 1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "slot", "operator": "=", "value": "SLOT 2" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SLOT 3 ACCURACY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "STATUS",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "measurement": "correctness",
     "query": "SELECT last(\"value\")  FROM \"availability\"  WHERE (\"slot\" = 'SLOT 1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "slot", "operator": "=", "value": "SLOT 3" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "SLOT 4 ACCURACY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "STATUS",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "measurement": "correctness",
     "query": "SELECT last(\"value\")  FROM \"availability\"  WHERE (\"slot\" = 'SLOT 1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "slot", "operator": "=", "value": "SLOT 4" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Parking Environments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 1, "y": 14 },
   "targets": [
    {
     "measurement": "safetymetrices",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "temperature" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 14 },
   "targets": [
    {
     "measurement": "safetymetrices",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "humidity" }
     ]
    }
   ]
  },
  {
   "title": "FHGas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 1, "y": 20 },
   "targets": [
    {
     "measurement": "safetymetrices",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "fhgas" }
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 20 },
   "targets": [
    {
     "measurement": "safetymetrices",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "eco2" }
     ]
    }
   ]
  },
  {
   "title": "TVOC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 1, "y": 26 },
   "targets": [
    {
     "measurement": "safetymetrices",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "tvoc" }
     ]
    }
   ]
  }
 ]
}